FROM python:3.9-alpine
WORKDIR /Autotests
COPY requirements.txt /Autotests
RUN pip3 install -r requirements.txt --no-cache-dir
COPY . /Autotests
ADD test_users.py /Autotests
ADD conftest.py /Autotests
CMD ["logic.py"]